# Generated by Django 3.0.2 on 2020-01-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
