# Generated by Django 3.0.2 on 2020-03-06 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationName', models.CharField(max_length=50)),
                ('donationDescription', models.TextField(blank=True)),
                ('donationDate', models.DateTimeField(auto_now_add=True)),
                ('donationAmount', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='sponsors',
            name='state',
        ),
        migrations.AddField(
            model_name='sponsors',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownername', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsors',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sponsors',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sponsors',
            name='zip',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docName', models.CharField(max_length=100)),
                ('docType', models.CharField(max_length=30)),
                ('docContent', models.TextField(blank=True)),
                ('lastEdited', models.DateTimeField(auto_now_add=True)),
                ('isTemplate', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateFirstName', models.CharField(max_length=100, null=True)),
                ('candidateLastName', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phoneNo', models.BigIntegerField()),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zip', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('candidateCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.CandidateCategory')),
                ('donationId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.Donations')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidateowner', to=settings.AUTH_USER_MODEL)),
                ('sponsorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.Sponsors')),
            ],
        ),
        migrations.AddField(
            model_name='sponsors',
            name='sponsorgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorgroupname', to='core.SponsorGroup'),
        ),
    ]
