# Generated by Django 3.0.2 on 2020-03-19 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200306_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='donationId',
        ),
        migrations.AddField(
            model_name='donations',
            name='donatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_name', to='core.Sponsors'),
        ),
        migrations.AddField(
            model_name='donations',
            name='donationTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_name', to='core.Candidates'),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='candidateCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatecategoryname', to='core.CandidateCategory'),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidateownername', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='sponsorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsoridname', to='core.Sponsors'),
        ),
    ]
