# Generated by Django 3.0.2 on 2020-01-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200111_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
