# Generated by Django 3.0.2 on 2020-01-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sponsors_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsors',
            old_name='state',
            new_name='region',
        ),
    ]
