# Generated by Django 3.0.2 on 2020-03-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200319_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='donatedBy',
        ),
        migrations.AddField(
            model_name='donations',
            name='donationBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_name', to='core.Sponsors'),
        ),
    ]
