# Generated by Django 3.0.2 on 2020-01-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200113_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='zip',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
