# Generated by Django 3.0.2 on 2020-03-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_donations_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='donationDate',
            field=models.DateTimeField(),
        ),
    ]
