# Generated by Django 3.0.2 on 2020-01-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sponsors_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
