# Generated by Django 3.0.2 on 2020-02-12 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_sponsors_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationName', models.CharField(max_length=50)),
                ('donationDescription', models.TextField(blank=True)),
                ('donationDate', models.DateTimeField(auto_now_add=True)),
                ('donationAmount', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docName', models.CharField(max_length=100)),
                ('docType', models.CharField(max_length=30)),
                ('docContent', models.TextField(blank=True)),
                ('lastEdited', models.DateTimeField(auto_now_add=True)),
                ('isTemplate', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateName', models.CharField(max_length=100)),
                ('candidateCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.CandidateCategory')),
                ('donationId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.Donations')),
                ('sponsorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.Sponsors')),
            ],
        ),
    ]
