# Generated by Django 3.0.2 on 2020-02-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200218_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='sponsorgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorgroupname', to='core.SponsorGroup'),
        ),
    ]
