# Generated by Django 3.0.2 on 2020-02-18 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_auto_20200218_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownername', to=settings.AUTH_USER_MODEL),
        ),
    ]
