export const GET_SPONSORS = "GET_SPONSORS";
export const DELETE_SPONSOR = "DELETE_SPONSOR";
export const EDIT_SPONSOR = "EDIT_SPONSOR";
export const ADD_SPONSOR = "ADD_SPONSOR";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";