//CLIENTS AND CORE
export const GET_SPONSORS = "GET_SPONSORS";
export const DELETE_SPONSOR = "DELETE_SPONSOR";
export const GET_SPONSOR = "GET_SPONSOR";
export const ADD_SPONSOR = "ADD_SPONSOR";
export const UPDATE_SPONSOR = "UPDATE_SPONSOR";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS= "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS= "REGISTER_SUCCESS";
export const REGISTER_FAILED= "REGISTER_FAILED";
export const GET_SPONSORGROUPS= "GET_SPONSORGROUPS";
export const GET_SPONSORGROUP= "GET_SPONSORGROUP";
export const ADD_SPONSORGROUP= "ADD_SPONSORGROUP";

//CANDIDATES
export const GET_CANDIDATES = "GET_CANDIDATES";
export const GET_CANDIDATECATEGORY = "GET_CANDIDATECATEGORY";
export const ADD_CANDIDATECATEGORY = "ADD_CANDIDATECATEGORY";
export const ADD_CANDIDATE = "ADD_CANDIDATE";
export const EDIT_CANDIDATE = "EDIT_CANDIDATE";
export const DELETE_CANDIDATE = "DELETE_CANDIDATE";