export const GET_SPONSORS = "GET_SPONSORS";
export const DELETE_SPONSOR = "DELETE_SPONSOR";
export const EDIT_SPONSOR = "EDIT_SPONSOR";
export const ADD_SPONSOR = "ADD_SPONSOR";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS= "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS= "REGISTER_SUCCESS";
export const REGISTER_FAILED= "REGISTER_FAILED";
export const GET_SPONSORGROUPS= "GET_SPONSORGROUPS";

